CHANGELOG.md, README.md, docs/dlt-logs/docs/reports.md, media/timeSeriesReport.html, package.json, src/dltReport.ts
If captured or converted data starts with "EVENT_" it will be drawn
as a "scatter"/event chart. So not using lines but single dots.
This works only for "float" values (yet).
Resolves: #3
=> First impl of "scatter"/events in reports

src/dltReport.ts
If messages had to be queued they've been dequeued in wrong order.
This should fix issue #7.
Issues: #7
=> fix(report): queued msgs to webview should be in fifo order

src/dltParser.ts
This change adds the mtin info string to the rest query result (e.g. info, warning, error, etc.).
=> feat: add mtin string to restquery results for msgs

README.md, package.json, src/adltDocumentProvider.ts, src/extension.ts
Added the path to the embedded adlt binary to the env PATH for embedded terminals.
Added command "New terminal with adlt in path" as well (a bit redundant
but ensure that the extension gets loaded first).
=> feat(adlt): add path to adlt to terminal

package.json, src/adltDocumentProvider.ts, src/dltDocumentProvider.ts, src/dltTreeViewNodes.ts, src/extension.ts
Button is visible only when no pos. filters are set, so the apid/ctid is
visible. This helps to set a pos. filter only showing those and not
removing only those messages.
=> feat: add button 'set pos filter' to treeview

src/extension.ts
To provent users settings it e.g. by mistake to "" or empty array always
- check for array
- check that dlt and asc are included.
=> fix(adlt): ensure fileExtensions contain dlt and asc

package.json
Previously plugins needed to be specified in the
exact sequence. This was never intended.
Now any of them can be specified.
Leaving a race-condition/misuse if the same plugin is specified multiple
times.
=> fix(config): plugins can be specified in any order

docs/dlt-logs/docs/reports.md, media/timeLinesChart.js, media/timeSeriesReport.html, src/dltReport.ts
Groups within timeline chart are now by default sorted alphabetically.
Additionally a groupPrio can be specified to sort groups at the begin (>0)
or at the end (<0) of the groups.
=> feat(report): add sorting of groups for timeline chart

package.json
To let the marketplace know that we do support that as well.
=> docs: add extension asc to package.json

src/extension.ts
Add adltProvider to disposables/subscriptions to close/stop the spawned
adlt process.
=> fix: close spawned process on extension deactivation

src/adltDocumentProvider.ts, src/extension.ts, src/generateRegex.ts, src/test/suite/generateRegex.test.ts, test/tsconfig.json, tsconfig.json
Add "open quick report" and "open regex101 with quick report" to hover popup for logs where a basic regex can be generated automatically. Currently supported are number values (floats).
=> feat(report): add quick report feature

src/adltDocumentProvider.ts, src/extension.ts, tsconfig.json
Add application/vnd.dlt-logs+json with filterFrags property on drag of a node that reflects one or more filter:
- "Filter": all active filter
- Plugin: set filter that would be set
- Single filter.
Dragging should work within same extension host only so mainly intended to work with fishbone extension.
=> feat: add drag for tree view filter nodes

src/ask_user.ts, src/quickPick.ts
Quickpick was completely disabled if the isValid value was not true. In prev. vscode versions this did just disable the "accept" but not any further entries.
At least with vsc 1.73 this seems changed.
=> fix: quickPick doesn't allow entries

src/adltDocumentProvider.ts
Toggling the sort order needs to invalidate the current lifecycle infos.
Issue: #115
=> fix: toggle sort order needs to clear lifecycle infos

media/regularGraphs.js, media/timeSeriesReport.html
If a single chart is drawn on resize/increase window size the chart is not redrawn/resized.
This seems to be due to
https://github.com/chartjs/Chart.js/issues/11139
Added a workaround by adding 2nd canvas.
This adds a small padding and thus invalidates the end-end tests but strangely helps to avoid the issue.
=> fix(report): hotfix to reenable zoom on resize

src/adltDocumentProvider.ts
Support onDidChangeConfiguration for filters instantly. Was/is supported for old js backend but not for adlt.
Implement for adlt as well.
=> feat: apply config changes for filters instantly

media/regularGraphs.js
Tooltips for scatter/events had a different title/label than regular ones. Made them the same:
- first line: time formatted
- 2nd line: dataset name: value
=> fix(report): tooltips for scatter/events

src/adltDocumentProvider.ts, src/extension.ts
If multiple log files have been opened as one document the quick filter and add filter from hover menu didn't work. Created https://github.com/microsoft/vscode/issues/179962 for vscode and added a workaround.
=> fix: quick report/add filter with multiple files

package-lock.json, package.json
Opening multiple CAN files lead to an overlap due to the "date" in .asc files having sec granularity only.
Fixed handling of those cases.
=> fix(can): multiple can files did wrongly overlap

docs/dlt-logs/docs/reports.md, package.json, src/adltDocumentProvider.ts, src/dltReport.ts
Add config setting dlt-logs.maxReportLogs and show a warning within the report if the limit is met and the report does show only a truncated amount of logs.
=> fix(report): show warning if truncation happens

package-lock.json, package.json
by spec but some client libs do so.
Add support for non-zero term strings and autodection for zero-terminated ones.
=> fix: dlt strings are non zero terminated

package-lock.json, package.json, src/extension.ts
Logcat files in default format e.g. "logcat -b all" stored with .txt extension can be opened as dlt files.
ECU will be dynamically assigned (LCxy)
Apid is an abbrevation of the tag incl. description. Ctid is fixed "LogC".
Opening multiple files might have some wrong sort order!
=> feat(logcat): add experimental support for logcat files

package-lock.json, package.json, src/adltDocumentProvider.ts, src/dltReport.ts, src/extension.ts
Import dlt-logs-utils as uv0 (utils version 0) for conversion functions. Allows e.g. return new TL('group','lane',matches[1], {color:'red'})
=> feat: add dlt-logs-utils support

docs/dlt-logs/docs/filterReference.mdx, package-lock.json, package.json, src/dltAddEditFilter.ts, src/dltFilter.ts, src/test/suite/dltFilter.test.ts, src/util.ts
Within filters the ecu, apid and ctid support regex either by: providing "ecuIsRegex:true, apidIsRegex:true, ctidIsRegex:true" or by autodetection if the ecu/apid/ctid values include any regex special chars like '|^$,...".
See docu "Filter reference".
=> feat: regex support for ecu, apid, ctid

package-lock.json, package.json, src/adltDocumentProvider.ts, src/panels/SearchPanel.ts
The reveal e.g. of search results was using the time in ms granularity only. This can be very coarse in cases of plenty of logs with similar times. Using the new binary_search by index from adlt 0.48.0 to get closer to the real msg.
=> fix: improve reveal accurracy

src/adltDocumentProvider.ts, src/adltPlugin.ts
Root cause where cases where due to the different order the text length did not change. Those cases did not lead to updates. Fixed by explicitly updating "mtime" on any text change.
=> fix: toggle sort order triggers no update of the document

src/panels/SearchPanel.ts
Avoid conversion via Date constructor that seems to loose sub ms precision.
=> fix(search): use full .1ms precision

package-lock.json, package.json, src/adltPlugin.ts
Add support for plugins to return per tree item an array of filterFrag(ments). Use adlt v0.50.0 that uses it for someip methods.
=> feat(plugin): support filterFrag array and use for someip methods

package-lock.json, package.json, src/adltDocumentProvider.ts, src/adltRemoteFsProvider.ts, src/extension.ts, src/quickPick.ts
Initial support for a real remote setup where adlt is running on a different machine.
Use command "Open DLT file via a remote adlt instance...". File selection dialog will open multiple times to be able to select multiple files at once.
Last address is persisted in globalState (global for that user).
The remote filesystem can be browsed during file open dialog at /fs/...
Currently e.g. the plugin paths need to fit as well to the remote machine. This needs better settings options.
=> feat(remote): add new command dltOpenAdltRemoteFile

src/panels/SearchPanel.ts
Multiple negative filter always remove all logs as the logic is:
- add logs matching any positive filter (or all if no pos.filters)
- remove logs matching any negative filter
- keep logs matching any event filter.
=> fix(search): use EVENT instead of !NEGATIVE filter type

package-lock.json, package.json
and fix date support with milliseconds.
Use adlt 0.56.2 which contains the two fixes.
=> fix(can): support asc files with multiple whitespaces

package-lock.json, package.json, src/adltComments.ts, src/adltDocumentProvider.ts
This allows to add comments (using the small '+' icon at the start of every log line) to a single log or a selected block of logs.
The comments can then be exported to the clipboard in Markup code, i.e. the log lines will be embedded in a {noformat} block. Currently comments are persisted only in the globalState of the extension so only on the local machine.
As storage key the URI (so indirectly the path/name of the files) are used. They comments are purged/deleted after >30days.
=> feat(comment): first minimal version of comments

package-lock.json, package.json, src/adltDocumentProvider.ts, src/adltRemoteFsProvider.ts, src/extension.ts, src/remote_types.ts
For windows currently .zip and multi-volume .zip.001 are supported. For mac .7z, .tgz, ... are supported as well.
Archive support is provided via adlt 0.58.0.
=> feat(unzip): support direct opening of zip archives

src/adltDocumentProvider.ts, src/test/suite/util.test.ts, src/util.ts
Slash/backslash handling for windows.
Currently adlt expect the path within the archive
always with / and not \\.
=> fix(unzip): normalize paths within multiple files

README.md, package-lock.json, package.json
Now the windows and the mac-arm version use
libarchive to support .7z, .bz2, .tar.gz, .tar.bz2 archives.
=> feat(unzip): add .7z, .bz2, ... to windows version

docs/dlt-logs/docs/reports.md, media/timeLinesChart.js, media/timeSeriesReport.html, package-lock.json, package.json
Introduce tlAll function that allows to represent timelines for multiple states in a single timeline with an overview inside the tooltip.
=> feat(report): use dlt-logs-utils v0.2.0 providing tlAll

.github/workflows/build_pr.yml, .github/workflows/build_tag.yml, README.md
and use node lts/* for npx vsce.
=> ci: package win32-arm64 as well

.vscodeignore
Have been lost with the change to esbuild.
As they are referenced from some html code esbuild can not detect those. Need to think about how to bundle those properly and reliably from the build itself.
=> fix(report): provide needed modules for report

package.json, src/adltDocumentProvider.ts, src/extension.ts
Add a command for the sequence tree view items to open the result as a markdown document and opening the preview to it as well.
=> feat(sequences): support open as doc/markdown preview

src/panels/SearchPanel.ts, webviews/search/src/App.css, webviews/search/src/App.tsx
As the search window is using a windowed list copying "all" content from there does not really copy all but only the shown/windowed ones.
Removed the default behaviour (context menu and ctrl/cmd+a, ctrl/cmd+c) and replaced by an own implementation that really copies the full result to clipboard. If not all messages are selected (via ctrl/cmd+a) then the default behaviour is kept.
=> feat(search): cmd/ctrl+a/c copies all search results to clipboard

src/dltFilter.ts
This is used by restQueries to indicate that the attr doesn't exist. Added support for ecu/apid/ctid to ignore null values.
=> fix(filter): support filter with ecu:null

src/extension.ts
At startup the active doc might be set before the other extension subscribes.
So on subscribe if a doc is set inform only the new subscriber about that doc.
=> fix(restquery): inform on subscribe about the active doc

webviews/search/src/App.tsx
Increased number of old items in search list to 200 (from 50).
Dont store new entries in the search entry history list if they extend a current one except if they extend with | symbol. E.g. from a, ab, abc -> only abc gets stored.
From a, a|b, a|bc -> only a and a|bc get stored.
=> feat(search): improve last used search list
