src/dltSomeIpPlugin.ts
src/fibexLoader.ts

Implemented parsing of array of unions.

fix(someip): support array of unions

---

src/adltDocumentProvider.ts

Filter configs are not supported yet. So disabling all filters with a config
for now.
Refactored the code to wait for startStream until the first EAC infos are
received to be able to activate the configs before streaming.

fix(adlt): disable filters with configs at startup

---

README.md
package-lock.json
package.json
src/adltDocumentProvider.ts
src/extension.ts

including CAN plugin support to decode the CAN payload via a fibex file.

feat(can): support opening on .asc CAN files

---

src/extension.ts

Prev code didn't cover the part if the setting is not available/not set.

fix: hotfix for error file_exts.push is not a function

---

docs/dlt-logs/docs/reports.md
media/timeSeriesReport.html
src/adltDocumentProvider.ts
src/dltDocument.ts
src/dltReport.ts

and show file names of logs used for that report.
Updated docu on the two ways to set a report title (boolean and string).

feat(report): support setting of title for report

---

package.json

feat(welcome): add welcome view when no DLT log file is opened

---

media/timeSeriesReport.html
src/adltDocumentProvider.ts

Was disabled by change to chartjs v3. Re-enabled.
Pinch is still disabled. If anybody missed this please file an issue.

fix(report): re-enable zoom by wheel

---

src/adltDocumentProvider.ts

Some cleanups of unused code.
Dumping mem usage every 10s to identify mem leak use-cases.
Dispose called for doc on close.

fix: dispose for doc called, mem dump, cleanups

---

.github/workflows/build.yml

ci: update setup-node version

---

media/timeSeriesReport.html

Now descriptions can be set for pinned annotations.

feat(report): descriptions for pinned annotations

---

src/adltDocumentProvider.ts
src/extension.ts

If the document kept on loading the restQueries - e.g. from fishbone extension -
have not been retriggered and thus showed an outdate status.
Now the retrigger will happen 3s after the last doc change.

fix(adlt): retigger restQueries if doc changes

---

docs/dlt-logs/docs/reports.md
media/timeLinesChart.js

and better algorithm to assign colors trying to keep each lane with as many
unique colors as possible.
Sort legend by group/lane.

feat(report): more colors for timeline legend

---

media/timeSeriesReport.html
src/dltReport.ts

If the yAxis is not specified instead of simply using the first scale
the following check is performed:
- if the data renders the main scale non significant (<0.1) or
- if the new data would be non-significant inside the existing scales
a new scale is used.

feat(report): auto-scale generation for non specified yaxis

---

package.json

pull-in adlt v0.28.2 that fixes the report for someip events with multiple parameter.

fix(adlt): fix someip event report

---

.github/workflows/build_pr.yml
package-lock.json
package.json
src/adltPlugin.ts

to get version with console file_transfer
and packages (as chore).

feat: update adlt

---

package-lock.json
package.json

Use adlt version 0.30.1 with startsWith support for BusMappings.

fix: can plugin busmappings

---

package-lock.json
package.json

if multiple fibex files provide partial frame info for same channels.

fix: can plugin missing frames

---

package.json

see https://docs.github.com/en/actions/using-workflows/workflow- commands-for-github-actions#environment-files

ci: replace set-output by env var

---

package-lock.json
package.json

Enables for CAN plugin automatic reports with enums/texttable/bitfields.

feat: adlt with can report enums

---

package-lock.json
package.json

CAN fibex files need the signal-instance is_high_low_byte_order support.

fix(CAN): upgrade adlt version with CAN endianess fix

---

media/regularGraphs.js
package-lock.json
package.json

Allow to open overlapping files e.g. can files from same times but for different channels.

feat: open time-wise overlapping files

---

.eslintrc.json
.github/workflows/build.yml
.github/workflows/build_pr.yml
.github/workflows/build_tag.yml
.vscodeignore
README.md
media/regularGraphs.js
package-lock.json
package.json
src/adltDocumentProvider.ts
src/extension.ts
src/panels/SearchPanel.ts
src/util.ts
tsconfig.json
webviews/search/.gitignore
webviews/search/index.html
webviews/search/package-lock.json
webviews/search/package.json
webviews/search/src/App.css
webviews/search/src/App.tsx
webviews/search/src/index.tsx
webviews/search/src/utilities/vscode.ts
webviews/search/src/vite-env.d.ts
webviews/search/tsconfig.json
webviews/search/vite.config.ts

Added command dlt-logs.search and a icon button to open the search panel.
Supports
- search within current content / with current filters active
- search within full file (no filters active)
- regex search.
Missing yet:
- case sensitive search (button currently non functional)
- using "window"/stream for large search results
- ... (see todos in webviews/search/src/App.tsx)
Issue: add search window similar to dlt-viewer #153

feat(search): add search panel/window

---

src/panels/SearchPanel.ts
webviews/search/src/App.tsx

...if terminal/panel area is not shown yet.

fix(search): search panel doesn't open on first press

---

webviews/search/src/App.tsx

Keep a list of up to 50 last used search strings.
Enter the list via
- arrow/cursor down key
- arrow down icon.
Delete entries from the list via selection and 'delete' key.

feat(search): add last used search dropdown

---

package-lock.json
package.json

Additionally to ASAM fibex files now franca_json files are supported as well. Simply put those files (additionally or instead) into the fibex_dir configured.

feat(someip): support franca_json files

---

docs/dlt-logs/docs/filterReference.mdx
package-lock.json
package.json

and fix some layout issues in docs.

fix(adlt): update to v0.44.0

---

package-lock.json
package.json

Treat S_INT8|16|32|64 as S_SINT8|16|32|64.

fix(nonverbose): add S_INTxy support

---

docs/dlt-logs/docs/someIpPlugin.md
media/regularGraphs.js
package-lock.json
package.json
src/dltReport.ts

and fix tooltip for state '0'.

fix(report): handle STATE_ with type number as strings

---

package-lock.json
package.json
src/adltDocumentProvider.ts
src/adltPlugin.ts
src/ask_user.ts
src/dltDocument.ts
src/dltDocumentProvider.ts
src/dltReport.ts
src/extension.ts
src/panels/SearchPanel.ts

Change console logging to output window 'DLT-Logs'. Increased min supported VSCode version to 1.83.0.

feat: output window 'DLT-Logs'

---

package-lock.json
package.json

and some minor package updates.

perf: use adlt 0.52.1 with performance improvements

---

src/panels/SearchPanel.ts

Fixed a race-condition that lead to multiple streams still running even though the stream was disposed.

fix(Search): deny requestNewWindow after dispose

---

package-lock.json
package.json
src/extension.ts

Use new adlt 0.55.1 that uses performance optimizations and includes support first support for generic text log files.

feat: basic support of text log files and performance opt

---

docs/dlt-logs/docs/exportAndFilter.md
package-lock.json
package.json
src/adltDocumentProvider.ts
src/adltExport.ts
src/dltExport.ts
src/extension.ts
src/quickPick.ts

This implementation is optimized to not keep msgs in ram thus supporting really huge files. Keeping old implementation as it has the sort/rewrite feature via the "Export/filter ... deprecated..." command.
Will add sort/rewrite later as part of a "export as..." feature.

feat(export): implement export feature using adlt

---

package-lock.json
package.json

fix(someip): dont stop parsing fibex on first service failure

---

package-lock.json
package.json
src/extension.ts

Support opening of .blf files as CAN msgs.

feat(blf): support opening of Vector binlog blf files

---

.github/workflows/build_pr.yml
.github/workflows/build_tag.yml
package-lock.json
package.json

ci: provide win32-x64 for win32-arm64
win32-arm64 can handle for now the win32 x64 binaries.

win32-arm64 target and adlt 0.61.1

---

package.json
src/adltDocumentProvider.ts
src/extension.ts

Copies the sequence result in markdown format
to the clipboard.

feat(sequence): add copy to clipboard for events/sequence

---

package-lock.json
package.json
src/adltDocumentProvider.ts

and add steps from sub-sequences into tree-view.

feat(sequence): add context support

---

package-lock.json
package.json

Update adlt version to improve output of control
messages incl.
bugfix for first byte of payload
being omitted.

feat(adlt): improve output for ctrl messages

---

package-lock.json
package.json

Added support for FLER error messages.
Reduce memory usage for file transfers.
Speed up tree item generation for lots of file transfers.

fix(adlt): update to 0.61.5 with file transfer plugin fixes

---

src/adltDocumentProvider.ts

Seems some extensions query the filesystem provider with readFile of .git/config files.
This is causing issues 'config' file shown in tree view and search/restquery not working
as config is then the active file.
Hotfix is to avoid opening uri with files inside archives that do not locally exist.
So opening any archive file that contain '.git/config' is currently not possible. Proper fix to handle the situation where a non existing relative path inside an archive is used for stat/readFile is needed.
Provided a clean solution for the Buffer.from warning as well via TextEncoder.

fix: hotfix to prevent .git/config files opened as document
